---
version: 2.1


jobs:

  ruby-26:
    docker:
      - image: circleci/ruby:2.6.3-node-browsers-legacy
        environment:
          PGHOST: localhost
          PGUSER: administrate
          RAILS_ENV: test
      - image: postgres:10.1-alpine
        environment:
          POSTGRES_USER: administrate
          POSTGRES_DB: ruby26
          POSTGRES_PASSWORD: ""

    working_directory: ~/administrate

    steps:
      - checkout
      - run: bundle install --path vendor/bundle
      - run: dockerize -wait tcp://localhost:5432 -timeout 1m
      - run: cp .sample.env .env
      - run: bundle exec rake db:setup
      - run: bundle exec rake


workflows:
  version: 2
  build:
    jobs:
      - ruby-26
