# This is a basic workflow to help you get started with Actions

name: Issue Label Notify
on:
  issues:
      types: [labeled]

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
        - uses: jenschelkopf/issue-label-notification-action@v1
          with:
             token: ${{ secrets.GITHUB_TOKEN }}
             recipients: |
                  help wanted=@jenschelkopf
                  documentation=@jenschelkopf @docs-team
