name: Containers

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    container: circleci/ruby:2.5.0-node-browsers

    env:
      PGHOST: postgres
      PGUSER: administrate
      RAILS_ENV: test

    services:
      postgres:
        image: postgres:10.1-alpine
        env:
          POSTGRES_USER: administrate
          POSTGRES_DB: ruby25
          POSTGRES_PASSWORD: ""
        ports:
        - 5432:5432
        # needed because the postgres container does not provide a healthcheck
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
    - name: Debugging env vars
      run: echo ${{ job.services.postgres }}
    - name: Setup file system permissions
      run: |
        sudo chown -R circleci $GITHUB_WORKSPACE
        sudo chmod -R 777 $GITHUB_WORKSPACE
    - uses: actions/checkout@v2
    - name: Build and test with Rake
      run: |
        bundle install --path vendor/bundle
        cp .sample.env .env
        bundle exec rake db:setup
        bundle exec rake
        bundle exec appraisal install
        bundle exec appraisal rake
