name: Browser Automation Tests
on: 
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning'
      tags:
        description: 'Test scenario tags'        

jobs:
  print_inputs:
    runs-on: ubuntu-latest
    steps:
    - name: Print context
      run: |
        echo "Payload: ${{ github.context }}"


    - run: |
        echo "Log level: ${{ github.event.inputs.logLevel }}"
        echo "Tags: ${{ github.event.inputs.tags }}" 


